Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  RepositoryName:
    Type: String

Resources:
# ECR
    BuildContainersRepository: 
      Type: AWS::ECR::Repository
      Properties: 
        RepositoryName: !Ref RepositoryName

Outputs:
  BuildContainersRepository:
    Value: !GetAtt BuildContainersRepository.Arn
    Description: Repository containing the build images
    Export: 
      Name: BuildContainersRepository