version: '2.0'
services:
  db:
    image: postgres:9.6.3
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/setup.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    ports:
       - "6379:6379"
 